controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    
    type: attribute

# See https://symfony.com/doc/current/routing.html
# api_me:
#         path: /api/me
#         methods: ['GET']
#         defaults:
#             _controller: '\App\Controller\MeController::fn_me'
#             _api_resource_class: 'App\Entity\User'
#             _api_collection_operation_name: 'collName_api_me'